### ISSUE TITLE
Still doesn't really work on macOS

### ISSUE THREAD

**Issue by codenyte** [mauro-balades/sf#3]
In my last issue, I reported a bug in the install script. That has been fixed, thank you very much, I appreciate that.

But I found another issue.
Now sf installs without any problems, but when you run it, it doesn't really work, because there is no `lscpu` command on macOS and no `uptime -p` option. `uptime` on macOS and I think on BSD, in general, doesn't have any flags.
I think that will be broken on FreeBSD too, maybe I will try it out later, but I don't know because I'm too lazy to install BSD.
Also, the colors don't work, and I don't know why. I thought it was because I use fish shell but I tried in both bash and fish and it didn't work either.

I tried to fix the uptime and I looked at the neofetch script and how it deals with uptime on macOS, and apparently, it uses
`sysctl -n kern.boottime` on macOS to get a value in seconds and then converts it into minutes/hour/days.
That would be complicated to implement and would require significant changes in the sf script.

For the CPU neofetch uses `sysctl -n machdep.cpu.brand_string` which on my system returns `Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz`
At least this value is usable and doesn't have to be formatted any further.
For the Colors, I don't have an idea yet, I will look into this later.

I don't have time right now, but later I will sit down and try to fix some of the issues, and if I find a solution I will submit a pull request.

**Comment by codenyte** [comment]
Update:
I thought that adding `export CLICOLOR=1` to /etc/profile would fix the issue with the colors, but it doesn't work.

**Comment by mauro-balades** [comment]
I will fix this, I am currently looking a way into replacing this linux commands with some commands that both support or even, check if the os is MacOS.

**Comment by mauro-balades** [comment]
Please tell me, does this work in macOS? `sysctl -a`

**Comment by mauro-balades** [comment]
tell me if the `lscpu` problem is fixed: https://github.com/mauro-balades/sf/commit/a54505d85f2a806323e66a1d2bfd1384f535b227

**Comment by mauro-balades** [comment]
and the uptime: https://github.com/mauro-balades/sf/commit/e60ee50b3eee060d4e4ca9bdcf3c47f9c64e1066

**Comment by mauro-balades** [comment]
and colors: https://github.com/mauro-balades/sf/commit/de4cf1e7f876c12eef15dfe82f7dea79cedbfead

**Comment by codenyte** [comment]
CPU and Uptime work perfect, but still no colors. Thank you very much for the fast response.

**Comment by mauro-balades** [comment]
what output do you get?

**Comment by codenyte** [comment]
![Screenshot](https://user-images.githubusercontent.com/39193783/166139735-c41e3e01-70e3-43bc-9d82-84865c4c16ba.png)

I just blured my username since it contains my real name and I don't want to share that on the Internet

**Comment by mauro-balades** [comment]
try now: https://github.com/mauro-balades/sf/commit/73dd7a3188bb8484b78c1efe7075a1adc2f7b372

btw, if you have a cute, little icon for macOS (ASCII art), I will add it instead of the UFO

**Comment by codenyte** [comment]
I will try it out tomorrow, I have to reinstall macOS because I accidentally removed all files from my /usr/local folder

**Comment by codenyte** [comment]
It's much better, but not completely fixed

![Screenshot](https://user-images.githubusercontent.com/39193783/166914003-8695e87e-62f1-4d37-90ea-41d8d91c9766.png)

**Comment by codenyte** [comment]
Regarding the ASCII Icon, you wrote that you already use some ASCII Art from ufetch, so I think you should use the macOS Icon from ufetch as well.

**Comment by mauro-balades** [comment]
> It's much better, but not completely fixed
> 
> ![Screenshot](https://user-images.githubusercontent.com/39193783/166914003-8695e87e-62f1-4d37-90ea-41d8d91c9766.png)

are colors allowed in your terminal?

**Comment by mauro-balades** [comment]
also, I can see that the scapes codes are not updated. Did u check that SF is completely updated?

**Comment by codenyte** [comment]
> are colors allowed in your terminal?
Yes, it works for all other CLI Applications

> also, I can see that the scapes codes are not updated. Did u check that SF is completely updated?
Yes, I deleted /usr/local/bin/sf and ~/.config/sf and then ran the install script

**Comment by mauro-balades** [comment]
hm...

**Comment by mauro-balades** [comment]
any ideas?

**Comment by codenyte** [comment]
Yes, it exists.
I looked into the config file and I saw that it contains values like `BGRAY="\e[1;30m"`
I changed it to `
BGREEN="\033[1;32m"
BMAGENTA="\033[1;35m"
BCYAN="\033[1;36m"
BBLUE="\033[1;34m"
BRED="\033[1;31m"
BGRAY="\033[1;30m"` and now it works.
![Screenshot](https://user-images.githubusercontent.com/39193783/168100439-3370cb68-eab3-48d3-9033-ad22cca368e7.png)

**Comment by mauro-balades** [comment]
oh... you are right! I forgot to change the config file also!!! I am really sorry.

**Comment by mauro-balades** [comment]
btw, did u liked the fetcher?

**Comment by mauro-balades** [comment]
btw, did u liked the fetcher?

**Comment by mauro-balades** [comment]
> I'm sorry, I didn't see your message.
> Yes I like sf, its a nice small fetcher and it does everything I need, and it's a great replacement for pfetch.

Thanks :)
