### ISSUE TITLE
A bug with sf

### ISSUE THREAD

**Issue by Sirko2975** [mauro-balades/sf#4]
<img width="879" alt="Screenshot 2023-05-14 at 09 15 18" src="https://github.com/mauro-balades/sf/assets/121972871/9f4c66a6-abbc-497a-93f7-531ce38fa97b">

Having an issue on macOS 13.3.1 M1.
As I understood, some "not found" logo and markdown error, but could be mistaking.

**Comment by mauro-balades** [comment]
Hello there. One way to fix this is going into the config file `~/.config/sf/config.sh` and edi the variable "CCOLOR=" to an empty string. https://github.com/mauro-balades/sf/blob/main/example/config.sh#L58
