### ISSUE TITLE
Arch ascii for you to add

### ISSUE THREAD

**Issue by lp-35** [mauro-balades/sf#5]
elif [ "$OS" == "Arch Linux" ]; then
        export ICON1="$BBLUE       /\       "
        export ICON2="$BBLUE      /  \      "
        export ICON3="$BBLUE     /\   \     "
        export ICON4="$BBLUE   /  __  \    "
	export ICON5="$BBLUE   /  (  )  \   "
	export ICON6="$BBLUE  / __|  |__ \  "
        export ICON7="$BBLUE /.\*      */.\ "
	export ICON8="$BBLUE"

It looks weird here, but on terminal it looks fine

**Comment by mauro-balades** [comment]
could you send it inside the \`\`\` code blocks?

**Comment by lp-35** [comment]
```
elif [ "$OS" == "Arch Linux" ]; then
        export ICON1="$BRED       /\       "
        export ICON2="$BRED      /  \      "
        export ICON3="$BRED     /\   \     "
        export ICON4="$BRED    /  __  \    "
	export ICON5="$BRED   /  (  )  \   "
	export ICON6="$BRED  / __|  |__ \  "
        export ICON7="$BRED /.\*      */.\ "
	export ICON8="$BRED"
```

**Comment by mauro-balades** [comment]
https://github.com/mauro-balades/sf/commit/d7033d82b65b289f004ac1e988323d7cf3733354 done. Please tell me if it works!
